export interface ICountry {
    isoCode: string;
    name: string;
}

const COUNTRIES_LIST: ICountry[] = [
    { isoCode: "IN", name: "India" },
    { isoCode: "US", name: "United States" },
    { isoCode: "GB", name: "United Kingdom" },
    { isoCode: "CA", name: "Canada" },
    { isoCode: "AU", name: "Australia" },
    { isoCode: "SG", name: "Singapore" },
    { isoCode: "AE", name: "United Arab Emirates" },
    { isoCode: "MY", name: "Malaysia" },
    { isoCode: "LK", name: "Sri Lanka" },
    { isoCode: "NP", name: "Nepal" },
    { isoCode: "DE", name: "Germany" },
    { isoCode: "FR", name: "France" },
    { isoCode: "NZ", name: "New Zealand" },
    { isoCode: "ZA", name: "South Africa" },
    { isoCode: "AF", name: "Afghanistan" },
    { isoCode: "AL", name: "Albania" },
    { isoCode: "DZ", name: "Algeria" },
    { isoCode: "AD", name: "Andorra" },
    { isoCode: "AO", name: "Angola" },
    { isoCode: "AG", name: "Antigua and Barbuda" },
    { isoCode: "AR", name: "Argentina" },
    { isoCode: "AM", name: "Armenia" },
    { isoCode: "AT", name: "Austria" },
    { isoCode: "AZ", name: "Azerbaijan" },
    { isoCode: "BS", name: "Bahamas" },
    { isoCode: "BH", name: "Bahrain" },
    { isoCode: "BD", name: "Bangladesh" },
    { isoCode: "BB", name: "Barbados" },
    { isoCode: "BY", name: "Belarus" },
    { isoCode: "BE", name: "Belgium" },
    { isoCode: "BZ", name: "Belize" },
    { isoCode: "BJ", name: "Benin" },
    { isoCode: "BT", name: "Bhutan" },
    { isoCode: "BO", name: "Bolivia" },
    { isoCode: "BA", name: "Bosnia and Herzegovina" },
    { isoCode: "BW", name: "Botswana" },
    { isoCode: "BR", name: "Brazil" },
    { isoCode: "BN", name: "Brunei" },
    { isoCode: "BG", name: "Bulgaria" },
    { isoCode: "BF", name: "Burkina Faso" },
    { isoCode: "BI", name: "Burundi" },
    { isoCode: "KH", name: "Cambodia" },
    { isoCode: "CM", name: "Cameroon" },
    { isoCode: "CV", name: "Cape Verde" },
    { isoCode: "CF", name: "Central African Republic" },
    { isoCode: "TD", name: "Chad" },
    { isoCode: "CL", name: "Chile" },
    { isoCode: "CN", name: "China" },
    { isoCode: "CO", name: "Colombia" },
    { isoCode: "KM", name: "Comoros" },
    { isoCode: "CG", name: "Congo" },
    { isoCode: "CR", name: "Costa Rica" },
    { isoCode: "HR", name: "Croatia" },
    { isoCode: "CU", name: "Cuba" },
    { isoCode: "CY", name: "Cyprus" },
    { isoCode: "CZ", name: "Czech Republic" },
    { isoCode: "DK", name: "Denmark" },
    { isoCode: "DJ", name: "Djibouti" },
    { isoCode: "DM", name: "Dominica" },
    { isoCode: "DO", name: "Dominican Republic" },
    { isoCode: "EC", name: "Ecuador" },
    { isoCode: "EG", name: "Egypt" },
    { isoCode: "SV", name: "El Salvador" },
    { isoCode: "GQ", name: "Equatorial Guinea" },
    { isoCode: "ER", name: "Eritrea" },
    { isoCode: "EE", name: "Estonia" },
    { isoCode: "ET", name: "Ethiopia" },
    { isoCode: "FJ", name: "Fiji" },
    { isoCode: "FI", name: "Finland" },
    { isoCode: "GA", name: "Gabon" },
    { isoCode: "GM", name: "Gambia" },
    { isoCode: "GE", name: "Georgia" },
    { isoCode: "GH", name: "Ghana" },
    { isoCode: "GR", name: "Greece" },
    { isoCode: "GD", name: "Grenada" },
    { isoCode: "GT", name: "Guatemala" },
    { isoCode: "GN", name: "Guinea" },
    { isoCode: "GW", name: "Guinea-Bissau" },
    { isoCode: "GY", name: "Guyana" },
    { isoCode: "HT", name: "Haiti" },
    { isoCode: "HN", name: "Honduras" },
    { isoCode: "HU", name: "Hungary" },
    { isoCode: "IS", name: "Iceland" },
    { isoCode: "ID", name: "Indonesia" },
    { isoCode: "IR", name: "Iran" },
    { isoCode: "IQ", name: "Iraq" },
    { isoCode: "IE", name: "Ireland" },
    { isoCode: "IL", name: "Israel" },
    { isoCode: "IT", name: "Italy" },
    { isoCode: "JM", name: "Jamaica" },
    { isoCode: "JP", name: "Japan" },
    { isoCode: "JO", name: "Jordan" },
    { isoCode: "KZ", name: "Kazakhstan" },
    { isoCode: "KE", name: "Kenya" },
    { isoCode: "KI", name: "Kiribati" },
    { isoCode: "KP", name: "North Korea" },
    { isoCode: "KR", name: "South Korea" },
    { isoCode: "KW", name: "Kuwait" },
    { isoCode: "KG", name: "Kyrgyzstan" },
    { isoCode: "LA", name: "Laos" },
    { isoCode: "LV", name: "Latvia" },
    { isoCode: "LB", name: "Lebanon" },
    { isoCode: "LS", name: "Lesotho" },
    { isoCode: "LR", name: "Liberia" },
    { isoCode: "LY", name: "Libya" },
    { isoCode: "LI", name: "Liechtenstein" },
    { isoCode: "LT", name: "Lithuania" },
    { isoCode: "LU", name: "Luxembourg" },
    { isoCode: "MK", name: "North Macedonia" },
    { isoCode: "MG", name: "Madagascar" },
    { isoCode: "MW", name: "Malawi" },
    { isoCode: "MV", name: "Maldives" },
    { isoCode: "ML", name: "Mali" },
    { isoCode: "MT", name: "Malta" },
    { isoCode: "MH", name: "Marshall Islands" },
    { isoCode: "MR", name: "Mauritania" },
    { isoCode: "MU", name: "Mauritius" },
    { isoCode: "MX", name: "Mexico" },
    { isoCode: "FM", name: "Micronesia" },
    { isoCode: "MD", name: "Moldova" },
    { isoCode: "MC", name: "Monaco" },
    { isoCode: "MN", name: "Mongolia" },
    { isoCode: "ME", name: "Montenegro" },
    { isoCode: "MA", name: "Morocco" },
    { isoCode: "MZ", name: "Mozambique" },
    { isoCode: "MM", name: "Myanmar" },
    { isoCode: "NA", name: "Namibia" },
    { isoCode: "NR", name: "Nauru" },
    { isoCode: "NL", name: "Netherlands" },
    { isoCode: "NI", name: "Nicaragua" },
    { isoCode: "NE", name: "Niger" },
    { isoCode: "NG", name: "Nigeria" },
    { isoCode: "NO", name: "Norway" },
    { isoCode: "OM", name: "Oman" },
    { isoCode: "PK", name: "Pakistan" },
    { isoCode: "PW", name: "Palau" },
    { isoCode: "PA", name: "Panama" },
    { isoCode: "PG", name: "Papua New Guinea" },
    { isoCode: "PY", name: "Paraguay" },
    { isoCode: "PE", name: "Peru" },
    { isoCode: "PH", name: "Philippines" },
    { isoCode: "PL", name: "Poland" },
    { isoCode: "PT", name: "Portugal" },
    { isoCode: "QA", name: "Qatar" },
    { isoCode: "RO", name: "Romania" },
    { isoCode: "RU", name: "Russia" },
    { isoCode: "RW", name: "Rwanda" },
    { isoCode: "KN", name: "Saint Kitts and Nevis" },
    { isoCode: "LC", name: "Saint Lucia" },
    { isoCode: "VC", name: "Saint Vincent and the Grenadines" },
    { isoCode: "WS", name: "Samoa" },
    { isoCode: "SM", name: "San Marino" },
    { isoCode: "ST", name: "Sao Tome and Principe" },
    { isoCode: "SA", name: "Saudi Arabia" },
    { isoCode: "SN", name: "Senegal" },
    { isoCode: "RS", name: "Serbia" },
    { isoCode: "SC", name: "Seychelles" },
    { isoCode: "SL", name: "Sierra Leone" },
    { isoCode: "SK", name: "Slovakia" },
    { isoCode: "SI", name: "Slovenia" },
    { isoCode: "SB", name: "Solomon Islands" },
    { isoCode: "SO", name: "Somalia" },
    { isoCode: "ES", name: "Spain" },
    { isoCode: "SD", name: "Sudan" },
    { isoCode: "SR", name: "Suriname" },
    { isoCode: "SZ", name: "Eswatini" },
    { isoCode: "SE", name: "Sweden" },
    { isoCode: "CH", name: "Switzerland" },
    { isoCode: "SY", name: "Syria" },
    { isoCode: "TJ", name: "Tajikistan" },
    { isoCode: "TZ", name: "Tanzania" },
    { isoCode: "TH", name: "Thailand" },
    { isoCode: "TL", name: "Timor-Leste" },
    { isoCode: "TG", name: "Togo" },
    { isoCode: "TO", name: "Tonga" },
    { isoCode: "TT", name: "Trinidad and Tobago" },
    { isoCode: "TN", name: "Tunisia" },
    { isoCode: "TR", name: "Turkey" },
    { isoCode: "TM", name: "Turkmenistan" },
    { isoCode: "TV", name: "Tuvalu" },
    { isoCode: "UG", name: "Uganda" },
    { isoCode: "UA", name: "Ukraine" },
    { isoCode: "UY", name: "Uruguay" },
    { isoCode: "UZ", name: "Uzbekistan" },
    { isoCode: "VU", name: "Vanuatu" },
    { isoCode: "VE", name: "Venezuela" },
    { isoCode: "VN", name: "Vietnam" },
    { isoCode: "YE", name: "Yemen" },
    { isoCode: "ZM", name: "Zambia" },
    { isoCode: "ZW", name: "Zimbabwe" }
];

export const Country = {
    getAllCountries: () => COUNTRIES_LIST,
    getCountryByCode: (code: string) => COUNTRIES_LIST.find(c => c.isoCode.toLowerCase() === code.toLowerCase())
};